### ISSUE TITLE
Config file deletes itself on restart

### ISSUE THREAD

**Issue by TheOpalium** [Eufranio/MagiBridge#100]
Hello!
I'm trying to run MagiBridge on my SpongeForge server, but unfortunately, I'm having some trouble.
Whenever I start the server, the config file just... clears itself. The file simply becomes completely blank. Even if I add in the original text (I copied it beforehand), the next time I restart the config file will be blank again.

I'm running SpongeForge 7.1.0 BETA-3341, but this has also happened with the recommended version on their website (3206).

Any idea what may be causing this?

**Comment by Eufranio** [comment]
Check your logs for any errors related to MagiBridge.

**Comment by TheOpalium** [comment]
This is the error I receive at server startup:
```
[04:53:08] [Server thread/INFO] [magibridge]: MagiBridge is starting!
[04:53:08] [Server thread/ERROR] [magibridge]: Could not load config.
java.lang.IllegalArgumentException: Configuration does not accept objects of type class com.magitechserver.magibridge.config.categories.ConfigCategory
	at ninja.leaping.configurate.ScalarConfigValue.setValue(ScalarConfigValue.java:51) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3341.jar:1.12.2-2705-7.1.0-BETA-3341]
	at ninja.leaping.configurate.SimpleConfigurationNode.insertNewValue(SimpleConfigurationNode.java:311) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3341.jar:1.12.2-2705-7.1.0-BETA-3341]
	at ninja.leaping.configurate.SimpleConfigurationNode.setValue(SimpleConfigurationNode.java:276) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3341.jar:1.12.2-2705-7.1.0-BETA-3341]
	at ninja.leaping.configurate.commented.SimpleCommentedConfigurationNode.setValue(SimpleCommentedConfigurationNode.java:87) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3341.jar:1.12.2-2705-7.1.0-BETA-3341]
	at ninja.leaping.configurate.commented.SimpleCommentedConfigurationNode.setValue(SimpleCommentedConfigurationNode.java:33) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3341.jar:1.12.2-2705-7.1.0-BETA-3341]
	at ninja.leaping.configurate.SimpleConfigurationNode.storeDefault(SimpleConfigurationNode.java:117) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3341.jar:1.12.2-2705-7.1.0-BETA-3341]
	at ninja.leaping.configurate.SimpleConfigurationNode.getValue(SimpleConfigurationNode.java:200) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3341.jar:1.12.2-2705-7.1.0-BETA-3341]
	at com.magitechserver.magibridge.config.ConfigManager.loadConfig(ConfigManager.java:53) [ConfigManager.class:?]
	at com.magitechserver.magibridge.MagiBridge.initStuff(MagiBridge.java:90) [MagiBridge.class:?]
	at com.magitechserver.magibridge.MagiBridge.init(MagiBridge.java:72) [MagiBridge.class:?]
	at org.spongepowered.common.event.listener.GamePostInitializationEventListener_MagiBridge_init30.handle(Unknown Source) [?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) [RegisteredListener.class:1.12.2-2705-7.1.0-BETA-3341]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3341]
	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:443) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3341]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3341]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:231) [SpongeImpl.class:1.12.2-2705-7.1.0-BETA-3341]
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:271) [SpongeMod.class:1.12.2-2705-7.1.0-BETA-3341]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:219) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by PulzHF** [comment]
I am getting the same error as above, running  2.4.6 with SF 3340 on F 2739

https://pastebin.com/yqdya4sf

**Comment by Eufranio** [comment]
The latest recommended build of Sponge should fix those issues. Update if you haven't already.
