### ISSUE TITLE
Could not pass MessageChannelEvent$Chat$Impl

### ISSUE THREAD

**Issue by sfxworks** [Eufranio/MagiBridge#113]
```
[03:28:35] [Server thread/ERROR] [Sponge]: Could not pass MessageChannelEvent$Chat$Impl to Plugin{id=magibridge, name=MagiBridge, version=2.5, description=A utility Discord <-> Minecraft chat relay plugin, source=/home/lapitos/server/./mods/plugins/MagiBridge-API7-2.5.jar}
```

This occurs when someone sends a chat from Minecraft to discord. Unable to make this work using sponge 1.12.2-2768-7.1.4 and 1.12.2-2705 for MagiBridge 2.5.

The same error occurs with your version marked for sponge v7
```
[03:34:35] [Server thread/ERROR] [Sponge]: Could not pass MessageChannelEvent$Chat$Impl to Plugin{id=magibridge, name=MagiBridge, version=2.4.5.1, description=A utility Discord <-> Minecraft chat relay plugin, authors=[Eufranio], source=/home/lapitos/server/./mods/plugins/MagiBridge-API7-2.4.5.1.jar}
        at com.magitechserver.magibridge.DiscordHandler.sendMessageToDiscord(DiscordHandler.java:102) ~[DiscordHandler.class:?]
        at com.magitechserver.magibridge.DiscordHandler.sendMessageToDiscord(DiscordHandler.java:108) ~[DiscordHandler.class:?]
        at com.magitechserver.magibridge.listeners.SpongeChatListener.onSpongeMessage(SpongeChatListener.java:56) ~[SpongeChatListener.class:?]
```

**Comment by Eufranio** [comment]
Post the rest of the error when using the 2.5 build please. You only posted the first line.

**Comment by sfxworks** [comment]
Here is the full stack trace associated with this error.

```
[17:43:11] [Server thread/ERROR] [Sponge]: Could not pass MessageChannelEvent$Chat$Impl to Plugin{id=magibridge, name=MagiBridge, version=2.4.5.1, description=A utility Discord <-> Minecraft chat relay plugin, authors=[Eufranio], source=/home/lapitos/server/./mods/plugins/MagiBridge-API7-2.4.5.1.jar}
net.dv8tion.jda.core.exceptions.InsufficientPermissionException: Cannot perform action due to a lack of Permission. Missing permission: MESSAGE_WRITE
	at net.dv8tion.jda.core.entities.impl.AbstractChannelImpl.checkPermission(AbstractChannelImpl.java:306) ~[AbstractChannelImpl.class:?]
	at net.dv8tion.jda.core.entities.impl.AbstractChannelImpl.checkPermission(AbstractChannelImpl.java:298) ~[AbstractChannelImpl.class:?]
	at net.dv8tion.jda.core.entities.impl.TextChannelImpl.sendMessage(TextChannelImpl.java:265) ~[TextChannelImpl.class:?]
	at com.magitechserver.magibridge.DiscordHandler.sendMessageToDiscord(DiscordHandler.java:102) ~[DiscordHandler.class:?]
	at com.magitechserver.magibridge.DiscordHandler.sendMessageToDiscord(DiscordHandler.java:108) ~[DiscordHandler.class:?]
	at com.magitechserver.magibridge.listeners.SpongeChatListener.onSpongeMessage(SpongeChatListener.java:56) ~[SpongeChatListener.class:?]
	at org.spongepowered.common.event.listener.ChatListener_SpongeChatListener_onSpongeMessage346.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2768-7.1.4]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2768-7.1.4]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:347) [SpongeModEventManager.class:1.12.2-2768-7.1.4]
	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:435) [SpongeModEventManager.class:1.12.2-2768-7.1.4]
	at net.minecraftforge.common.ForgeHooks.onServerChatEvent(ForgeHooks.java:1766) [ForgeHooks.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:942) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-2768-7.1.4]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlg000(SourceFile:539) [hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:294) [SpongeImplHooks.class:1.12.2-2768-7.1.4]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjk000(MinecraftServer.java:3970) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by sfxworks** [comment]
After granting channel overrides, this was repaired. It was not immediately noticed.
