### ISSUE TITLE
A few random users cannot join

### ISSUE THREAD

**Issue by sfxworks** [Eufranio/MagiBridge#116]
For some reason, a user is not able to join after setting up our bungee server. This is just happening to 1,  but it seems to source from your plugin. Here's what happens after bungee passes the connection to the active server.

```
[08:55:58] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Awesome_Possum55 lost connection: Disconnected
[08:55:58] [Server thread/ERROR] [Sponge]: Could not pass ClientConnectionEvent$Disconnect$Impl to Plugin{id=magibridge, name=MagiBridge, version=2.4.5.1, description=A utility Discord <-> Minecraft chat relay plugin, authors=[Eufranio], source=/server/./mods/plugins/MagiBridge-API7-2.4.5.1.jar}
java.lang.IllegalArgumentException: Provided text for message may not be empty
        at net.dv8tion.jda.core.utils.Checks.notEmpty(Checks.java:52) ~[Checks.class:?]
        at net.dv8tion.jda.core.entities.MessageChannel.sendMessage(MessageChannel.java:185) ~[MessageChannel.class:?]
        at net.dv8tion.jda.core.entities.impl.TextChannelImpl.sendMessage(TextChannelImpl.java:266) ~[TextChannelImpl.class:?]
        at com.magitechserver.magibridge.DiscordHandler.sendMessageToChannel(DiscordHandler.java:34) ~[DiscordHandler.class:?]
        at com.magitechserver.magibridge.listeners.SpongeLoginListener.onQuit(SpongeLoginListener.java:57) ~[SpongeLoginListener.class:?]
        at org.spongepowered.common.event.listener.DisconnectListener_SpongeLoginListener_onQuit341.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2768-7.1.4]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2768-7.1.4]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:347) [SpongeModEventManager.class:1.12.2-2768-7.1.4]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:435) [SpongeModEventManager.class:1.12.2-2768-7.1.4]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2768-7.1.4]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:458) [SpongeEventManager.class:1.12.2-2768-7.1.4]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:242) [SpongeImpl.class:1.12.2-2768-7.1.4]
        at net.minecraft.network.NetHandlerPlayServer.redirect$onDisconnectHandler$zio000(NetHandlerPlayServer.java:2405) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:847) [pa.class:?]
        at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:457) [gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[08:55:58] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Awesome_Possum55 left the game

```

**Comment by sfxworks** [comment]
Might be something else client side thats disconnecting them. Then this plugin is not handling their odd disconnect.

**Comment by sfxworks** [comment]
source is player data corruption but leaving this open for you if you wanted to handle the output it provides

**Comment by Eufranio** [comment]
`Provided text for message may not be empty`: this could only be caused when the quit message in the config is empty on your side. I've added a check for this though.
