### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by bigenergy** [Eufranio/MagiBridge#151]
` [02:03:42] [pool-2-thread-5/ERROR] [Sponge]: The Scheduler tried to run the task magibridge-A-495 owned by Plugin{id=magibridge, name=MagiBridge, version=2.8.2, description=A utility Discord <-> Minecraft chat relay plugin, authors=[Eufranio], source=/root/rpg/./mods/plugins/MagiBridge-API7-2.8.2.jar}, but an error occured.
java.lang.NoClassDefFoundError: Could not initialize class okhttp3.OkHttpClient
        at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:482) ~[OkHttpClient$Builder.class:?]
        at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:855) ~[JDABuilder.class:?]
        at com.magitechserver.magibridge.MagiBridge.initJDA(MagiBridge.java:196) ~[MagiBridge.class:?]
        at com.magitechserver.magibridge.MagiBridge.lambda$initStuff$4(MagiBridge.java:109) ~[MagiBridge.class:?]
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2838-7.1.7-RC3944]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192) ~[SchedulerBase.class:1.12.2-2838-7.1.7-RC3944]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_211]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]`

MagiBrige v2.8.2

**Comment by Eufranio** [comment]
You might have an other version of JDA loaded, please post your plugin list.

**Comment by Mister172004** [comment]
Yo tambien tengo el mismo problema
Utilizo:
-spongeforge-1.12.2-2838-7.1.7-RC3948
Plugins:
-Nucleus
-MagiBridge (Ultima versión)

**Comment by Mister172004** [comment]
Yo, lo solucioné actualizando el complemento: "Nucleus"

**Comment by alowave223** [comment]
![image](https://user-images.githubusercontent.com/49539029/68898773-cef5ce00-0738-11ea-8b06-2a61c9591ef7.png)
![image](https://user-images.githubusercontent.com/49539029/68898781-d6b57280-0738-11ea-833f-5029d07fbef6.png)


> You might have an other version of JDA loaded, please post your plugin list.

**Comment by Xophys** [comment]
I get this problem when running the OpenFM mod on SpongeForge (because OpenFM deploys first)

**Comment by Xophys** [comment]
Oops. Forgot my Error Log

[21:39:31] [pool-3-thread-1/ERROR] [Sponge]: The Scheduler tried to run the task magibridge-A-0 owned by Plugin{id=magibridge, name=MagiBridge, version=2.8.2, description=A utility Discord <-> Minecraft chat relay plugin, authors=[Eufranio], source=.\mods\B[PLUGIN] MagiBridge-API7-2.8.2.jar}, but an error occured.
java.lang.NoSuchMethodError: okio.ByteString.startsWith(Lokio/ByteString;)Z
	at okio.Options.of(Options.java:64) ~[Options.class:?]
	at okhttp3.internal.Util.<clinit>(Util.java:73) ~[Util.class:?]
	at okhttp3.OkHttpClient.<clinit>(OkHttpClient.java:127) ~[OkHttpClient.class:?]
	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:482) ~[OkHttpClient$Builder.class:?]
	at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:855) ~[JDABuilder.class:?]
	at com.magitechserver.magibridge.MagiBridge.initJDA(MagiBridge.java:196) ~[MagiBridge.class:?]
	at com.magitechserver.magibridge.MagiBridge.lambda$initStuff$4(MagiBridge.java:109) ~[MagiBridge.class:?]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2838-7.1.7-RC3903]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192) ~[SchedulerBase.class:1.12.2-2838-7.1.7-RC3903]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_221]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_221]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]

**Comment by Eufranio** [comment]
Please try with the new version.

**Comment by Xophys** [comment]
I personally tried with 2.9 but with similar issue:

`pool-3-thread-6/ERROR 15:01:39
The Scheduler tried to run the task magibridge-A-28 owned by Plugin{id=magibridge, name=MagiBridge, version=2.9, description=A utility Discord <-> Minecraft chat relay plugin, authors=[Eufranio], source=./mods/[PLUGIN]: MagiBridge-API7-2.9.jar}, but an error occured.
Console 15:01:39
java.lang.NoSuchMethodError: okio.ByteString.startsWith(Lokio/ByteString;)Z
at okio.Options.of(Options.java:64) ~[Options.class:?]
at okhttp3.internal.Util.<clinit>(Util.java:73) ~[Util.class:?]
at okhttp3.OkHttpClient.<clinit>(OkHttpClient.java:127) ~[OkHttpClient.class:?]
at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:482) ~[OkHttpClient$Builder.class:?]
at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:855) ~[JDABuilder.class:?]
at com.magitechserver.magibridge.MagiBridge.initJDA(MagiBridge.java:209) ~[MagiBridge.class:?]
at com.magitechserver.magibridge.MagiBridge.lambda$initStuff$4(MagiBridge.java:116) ~[MagiBridge.class:?]
at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2838-7.1.7-RC3903]
at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192) ~[SchedulerBase.class:1.12.2-2838-7.1.7-RC3903]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_232]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_232]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]`
