### ISSUE TITLE
Hooking into Ultimate Chat not working for me.

### ISSUE THREAD

**Issue by so1ch1ro** [Eufranio/MagiBridge#223]
I've properly set up UC and it loads in for me but I keep getting this message in my console:

04.05 15:28:10 [Server] JDA MainWS-ReadThread/INFO [magibridge.net.dv8tion.jda.api.JDA]: Finished Loading!
04.05 15:28:10 [Server] pool-3-thread-3/INFO [magibridge]: Hooking into UltimateChat
04.05 15:28:11 [Server] pool-3-thread-3/ERROR [magibridge]: Error loading MagiBridge: 
04.05 15:28:11 [Server] INFO java.lang.NullPointerException: null
04.05 15:28:11 [Server] INFO at com.magitechserver.magibridge.discord.DiscordMessageBuilder.parsePlaceholders(DiscordMessageBuilder.java:221) ~[DiscordMessageBuilder.class:?]
04.05 15:28:11 [Server] INFO at com.magitechserver.magibridge.discord.DiscordMessageBuilder.get(DiscordMessageBuilder.java:123) ~[DiscordMessageBuilder.class:?]
04.05 15:28:11 [Server] INFO at com.magitechserver.magibridge.discord.DiscordMessageBuilder.send(DiscordMessageBuilder.java:174) ~[DiscordMessageBuilder.class:?]
04.05 15:28:11 [Server] INFO at com.magitechserver.magibridge.MagiBridge.lambda$onStartingServer$3(MagiBridge.java:95) ~[MagiBridge.class:?]
04.05 15:28:11 [Server] INFO at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:719) ~[?:1.8.0_265]
04.05 15:28:11 [Server] INFO at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701) ~[?:1.8.0_265]
04.05 15:28:11 [Server] INFO at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_265]
04.05 15:28:11 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1646) ~[?:1.8.0_265]
04.05 15:28:11 [Server] INFO at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2838-7.3.0]
04.05 15:28:11 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:197) ~[SchedulerBase.class:1.12.2-2838-7.3.0]
04.05 15:28:11 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_265]
04.05 15:28:11 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_265]
04.05 15:28:11 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
04.05 15:28:11 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
04.05 15:28:11 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]

I've tried a lot of fixes to this error, creating 2 bots for Magibridge and UC, redo-ing both configs, etc.
If you need more info than this I can send it.

**Comment by so1ch1ro** [comment]
[Magibridge.txt](https://github.com/Eufranio/MagiBridge/files/6423762/Magibridge.txt)
Also when typing something in chat it runs these errors EVERY time something is said.

**Comment by so1ch1ro** [comment]
sloved.
