### ISSUE TITLE
Error on plugins reload

### ISSUE THREAD

**Issue by LemADEC** [Eufranio/MagiBridge#47]
As of MagiBridge-2.4.1-all.jar and spongeforge-1.12.2-2529-7.0.0-BETA-2730.jar, when trying to reload the plugins, several errors are reported:
```
>sponge plugins reload
[19:27:35] [Server thread/INFO] [nucleus]: Server ran the command: /sponge plugins reload
[19:27:35] [Server thread/INFO]: Sending reload event to all plugins. Please wait.
[19:27:35] [Server thread/INFO] [magibridge]: Disconnecting from Discord...
[19:27:35] [Server thread/INFO] [magibridge]: Plugin stopped successfully!
[19:27:35] [Server thread/INFO] [magibridge]: MagiBridge is starting!
[19:27:35] [Server thread/INFO] [net.dv8tion.jda.core.JDA]: Login Successful!
[19:27:35] [JDA MainWS-WriteThread/INFO] [net.dv8tion.jda.core.requests.WebSocketClient]: Connected to WebSocket
[19:27:36] [JDA MainWS-ReadThread/INFO] [net.dv8tion.jda.core.JDA]: Finished Loading!
[19:27:36] [Server thread/INFO] [magibridge]: Hooking into Nucleus
[19:27:36] [Server thread/WARN] [Sponge]: Plugin magibridge attempted to register an already registered listener (com.magitechserver.magibridge.listeners.DeathListener)
[19:27:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: java.lang.Exception: Stack trace
[19:27:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]:    at java.lang.Thread.dumpStack(Thread.java:1336)
[19:27:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]:    at org.spongepowered.common.event.SpongeEventManager.registerListener(SpongeEventManager.java:217)
[19:27:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]:    at org.spongepowered.common.event.SpongeEventManager.registerListeners(SpongeEventManager.java:287)
[19:27:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]:    at com.magitechserver.magibridge.MagiBridge.initStuff(MagiBridge.java:128)
[19:27:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]:    at com.magitechserver.magibridge.MagiBridge.reload(MagiBridge.java:107)
[19:27:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]:    at org.spongepowered.common.event.listener.GameReloadEventListener_MagiBridge_reload26.handle(Unknown Source)
[19:27:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]:    at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
[19:27:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]:    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:316)
[19:27:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]:    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:349)
[19:27:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]:    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:333)
[19:27:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]:    at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:198)
[19:27:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]:    at org.spongepowered.common.command.SpongeCommandFactory.lambda$createSpongePluginsCommand$7(SpongeCommandFactory.java:517)
[19:27:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]:    at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:181)
[19:27:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]:    at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:360)
[19:27:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]:    at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:342)
[19:27:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]:    at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:321)
[19:27:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]:    at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083)
[19:27:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]:    at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:432)
[19:27:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]:    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
[19:27:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]:    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
[19:27:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]:    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
[19:27:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]:    at java.lang.Thread.run(Thread.java:748)
[19:27:36] [Server thread/INFO] [magibridge]: Plugin reloaded successfully!
```

**Comment by Eufranio** [comment]
Please try using this build: http://ci.heyzeer0.cf/job/MagiBridge/job/API-7/lastSuccessfulBuild/artifact/build/libs/MagiBridge-API7-2.4.1-b9.jar

**Comment by LemADEC** [comment]
Seems to work a bit better, still some errors showing up:
```
>sponge plugins reload
[19:36:55] [Server thread/INFO] [nucleus]: Server ran the command: /sponge plugins reload
[19:36:55] [Server thread/INFO]: Sending reload event to all plugins. Please wait.
[19:36:55] [Server thread/INFO] [magibridge]: Disconnecting from Discord...
[19:36:55] [Server thread/INFO] [magibridge]: Plugin stopped successfully!
[19:36:55] [Server thread/INFO] [magibridge]: MagiBridge is starting!
[19:36:55] [Server thread/INFO] [net.dv8tion.jda.core.JDA]: Login Successful!
[19:36:56] [JDA MainWS-WriteThread/INFO] [net.dv8tion.jda.core.requests.WebSocketClient]: Connected to WebSocket
[19:36:56] [MagiBridge Topic Updater/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.IllegalStateException: The Requester has been shutdown! No new requests can be requested!
[19:36:56] [MagiBridge Topic Updater/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at net.dv8tion.jda.core.requests.Requester.request(Requester.java:77)
[19:36:56] [MagiBridge Topic Updater/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at net.dv8tion.jda.core.requests.RestAction.queue(RestAction.java:284)
[19:36:56] [MagiBridge Topic Updater/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at net.dv8tion.jda.core.requests.RestAction.queue(RestAction.java:244)
[19:36:56] [MagiBridge Topic Updater/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at com.magitechserver.magibridge.util.TopicUpdater.run(TopicUpdater.java:35)
[19:36:56] [JDA MainWS-ReadThread/INFO] [net.dv8tion.jda.core.JDA]: Finished Loading!
[19:36:56] [Server thread/INFO] [magibridge]: Hooking into Nucleus
[19:36:56] [Server thread/INFO] [magibridge]: Plugin reloaded successfully!
```

**Comment by Eufranio** [comment]
Nothing I can do about that right now.

**Comment by LemADEC** [comment]
I'm not sure what the websocket option is supposed to be used for, so I've disabled it.
Is that related?

**Comment by Eufranio** [comment]
No, you can ignore that message.

**Comment by LemADEC** [comment]
ok, thanks
