### ISSUE TITLE
Chat not going through with Sponge API 7

### ISSUE THREAD

**Issue by LemADEC** [Eufranio/MagiBridge#51]
As of MagiBridge-2.4.2.jar with mods/spongeforge-1.12.2-2555-7.0.0-BETA-2757.jar, chat messages are not being transferred from in-game to the discord channels.
When bridge or a human writes to the discord channel, the following console error appears:
```
[17:45:14] [Server thread/INFO]: LemADEC joined the game
[17:45:16] [JDA MainWS-ReadThread/ERROR] [net.dv8tion.jda.core.JDA]: One of the EventListeners had an uncaught exception
[17:45:16] [JDA MainWS-ReadThread/ERROR] [net.dv8tion.jda.core.JDA]: Encountered an Exception
java.lang.NoClassDefFoundError: org/spongepowered/api/event/cause/NamedCause
>       at com.magitechserver.magibridge.discord.MessageListener.onMessageReceived(MessageListener.java:28) ~[MessageListener.class:?]
>       at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:404) ~[ListenerAdapter.class:?]
>       at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84) [InterfacedEventManager.class:?]
>       at net.dv8tion.jda.core.handle.MessageCreateHandler.handleDefaultMessage(MessageCreateHandler.java:128) [MessageCreateHandler.class:?]
>       at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:49) [MessageCreateHandler.class:?]
>       at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37) [SocketHandler.class:?]
>       at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:969) [WebSocketClient.class:?]
>       at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:661) [WebSocketClient.class:?]
>       at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352) [ListenerManager.class:?]
>       at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:260) [ReadingThread.class:?]
>       at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:238) [ReadingThread.class:?]
>       at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:963) [ReadingThread.class:?]
>       at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:746) [ReadingThread.class:?]
>       at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) [ReadingThread.class:?]
>       at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) [ReadingThread.class:?]
>       at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) [WebSocketThread.class:?]
[17:45:32] [Server thread/INFO]: Admin LemADEC: test
[17:45:54] [Server thread/INFO]: Admin LemADEC: test
```

When a player talk in-game (here above with Nucleus-1.2.0-PR4-S7.0-MC1.12.2-plugin.jar, there's no error in console nor message showing up Discord channel.

**Comment by Eufranio** [comment]
Use the API7 jar (its on the release tab, make sure you read it).
