### ISSUE TITLE
Plugin error 1.12.2

### ISSUE THREAD

**Issue by Jengas** [Eufranio/MagiBridge#53]
I am having this error when launching any plugin version
`[19:06:21] [Server thread/ERROR] [Sponge]: Could not pass GamePostInitializationEvent$Impl to Plugin{id=magibridge, name=MagiBridge, version=2.4.1, description=A utility Discord <-> Minecraft chat relay plugin, authors=[Eufranio], source=mods\MagiBridge-2.4.1-all.jar}
java.lang.NoClassDefFoundError: gnu/trove/map/TLongObjectMap
	at net.dv8tion.jda.core.utils.cache.impl.AbstractCacheView.<init>(AbstractCacheView.java:31) ~[AbstractCacheView.class:?]
	at net.dv8tion.jda.core.utils.cache.impl.SnowflakeCacheViewImpl.<init>(SnowflakeCacheViewImpl.java:28) ~[SnowflakeCacheViewImpl.class:?]
	at net.dv8tion.jda.core.entities.impl.JDAImpl.<init>(JDAImpl.java:66) ~[JDAImpl.class:?]
	at net.dv8tion.jda.core.JDABuilder.buildAsync(JDABuilder.java:523) ~[JDABuilder.class:?]
	at net.dv8tion.jda.core.JDABuilder.buildBlocking(JDABuilder.java:564) ~[JDABuilder.class:?]
	at com.magitechserver.magibridge.MagiBridge.initJDA(MagiBridge.java:198) ~[MagiBridge.class:?]
	at com.magitechserver.magibridge.MagiBridge.initStuff(MagiBridge.java:117) ~[MagiBridge.class:?]
	at com.magitechserver.magibridge.MagiBridge.init(MagiBridge.java:96) ~[MagiBridge.class:?]
	at org.spongepowered.common.event.listener.GamePostInitializationEventListener_MagiBridge_init13.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-7.0.0-BETA-374]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:371) [SpongeEventManager.class:1.12.2-7.0.0-BETA-374]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:388) [SpongeEventManager.class:1.12.2-7.0.0-BETA-374]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:392) [SpongeEventManager.class:1.12.2-7.0.0-BETA-374]
	at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:204) [SpongeImpl.class:1.12.2-7.0.0-BETA-374]
	at org.spongepowered.server.SpongeVanilla.initialize(SpongeVanilla.java:149) [SpongeVanilla.class:1.12.2-7.0.0-BETA-374]
	at net.minecraft.server.dedicated.DedicatedServer.handler$onServerInitialize$zol000(SourceFile:1243) [nz.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:191) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:434) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.ClassNotFoundException: gnu.trove.map.TLongObjectMap
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
	... 19 more
Caused by: java.lang.NullPointerException
[19:06:21] [Server thread/INFO] [Sponge]: Successfully loaded and initialized plugins.`

**Comment by Eufranio** [comment]
Fixed on latest build.
