### ISSUE TITLE
Error Realying Chat back to Minecraft

### ISSUE THREAD

**Issue by rouing** [Eufranio/MagiBridge#54]
`> [22:50:03] [JDA MainWS-ReadThread/ERROR] [net.dv8tion.jda.core.JDA]: Encountered an Exception
java.lang.NoClassDefFoundError: org/spongepowered/api/event/cause/NamedCause
at com.magitechserver.magibridge.discord.MessageListener.onMessageReceived(MessageListener.java:28) ~[MessageListener.class:?]
at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:404) ~[ListenerAdapter.class:?]
at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84) [InterfacedEventManager.class:?]
at net.dv8tion.jda.core.handle.MessageCreateHandler.handleDefaultMessage(MessageCreateHandler.java:128) [MessageCreateHandler.class:?]
at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:49) [MessageCreateHandler.class:?]
at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37) [SocketHandler.class:?]
at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:969) [WebSocketClient.class:?]
at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:661) [WebSocketClient.class:?]
at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352) [ListenerManager.class:?]
at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:260) [ReadingThread.class:?]
at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:238) [ReadingThread.class:?]
at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:963) [ReadingThread.class:?]
at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:746) [ReadingThread.class:?]
at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) [ReadingThread.class:?]
at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) [ReadingThread.class:?]
at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) [WebSocketThread.class:?]`

**Comment by Eufranio** [comment]
Use the API7 jar, not the normal one. Check the releases tab.
