### ISSUE TITLE
Server stopping messages don't get sent if topic updating is enabled

### ISSUE THREAD

**Issue by morrissimo** [Eufranio/MagiBridge#56]
Seeing errors like this in the console during a shutdown:
```
17.01 23:19:12 [Server] MagiBridge Topic Updater/ERROR [magibridge]: Something interrupted the topic updater!
17.01 23:19:12 [Server] Server thread/INFO [magibridge]: Disconnecting from Discord...
17.01 23:19:12 [Server] Server thread/INFO [magibridge]: Plugin stopped successfully!
17.01 23:19:12 [Server] JDA RateLimit-Queue Pool - Thread 2/ERROR [net.dv8tion.jda.core.requests.Requester]: Encountered an Exception 
17.01 23:19:12 [Server] INFO java.io.InterruptedIOException: thread interrupted
17.01 23:19:12 [Server] INFO at okio.Timeout.throwIfReached(Timeout.java:145) ~[Timeout.class:?]
17.01 23:19:12 [Server] INFO at okio.Okio$1.write(Okio.java:76) ~[Okio$1.class:?]
17.01 23:19:12 [Server] INFO at okio.AsyncTimeout$1.write(AsyncTimeout.java:180) ~[AsyncTimeout$1.class:?]
17.01 23:19:12 [Server] INFO at okio.RealBufferedSink.flush(RealBufferedSink.java:216) ~[RealBufferedSink.class:?]
17.01 23:19:12 [Server] INFO at okhttp3.internal.http1.Http1Codec.finishRequest(Http1Codec.java:166) ~[Http1Codec.class:?]
17.01 23:19:12 [Server] INFO at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72) ~[CallServerInterceptor.class:?]
17.01 23:19:12 [Server] INFO at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[RealInterceptorChain.class:?]
17.01 23:19:12 [Server] INFO at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[ConnectInterceptor.class:?]
17.01 23:19:12 [Server] INFO at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[RealInterceptorChain.class:?]
17.01 23:19:12 [Server] INFO at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[RealInterceptorChain.class:?]
17.01 23:19:12 [Server] INFO at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[CacheInterceptor.class:?]
17.01 23:19:12 [Server] INFO at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[RealInterceptorChain.class:?]
17.01 23:19:12 [Server] INFO at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[RealInterceptorChain.class:?]
17.01 23:19:12 [Server] INFO at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[BridgeInterceptor.class:?]
17.01 23:19:12 [Server] INFO at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[RealInterceptorChain.class:?]
17.01 23:19:12 [Server] INFO at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120) ~[RetryAndFollowUpInterceptor.class:?]
17.01 23:19:12 [Server] INFO at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[RealInterceptorChain.class:?]
17.01 23:19:12 [Server] INFO at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[RealInterceptorChain.class:?]
17.01 23:19:12 [Server] INFO at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185) ~[RealCall.class:?]
17.01 23:19:12 [Server] INFO at okhttp3.RealCall.execute(RealCall.java:69) ~[RealCall.class:?]
17.01 23:19:12 [Server] INFO at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:155) [Requester.class:?]
17.01 23:19:12 [Server] INFO at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:87) [Requester.class:?]
17.01 23:19:12 [Server] INFO at net.dv8tion.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:316) [BotRateLimiter$Bucket.class:?]
17.01 23:19:12 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
17.01 23:19:12 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
17.01 23:19:12 [Server] INFO at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_152]
17.01 23:19:12 [Server] INFO at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_152]
17.01 23:19:12 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
17.01 23:19:12 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
17.01 23:19:12 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
17.01 23:19:12 [Server] INFO Exception in thread "Server Shutdown Thread" 
17.01 23:19:12 [Multicraft] Server shut down (stopping)
17.01 23:19:12 [Multicraft] Server stopped
```
And, of course: no "server stopping" messages ever post to the target discord channel

**Comment by Eufranio** [comment]
How many bot applications are you running under the same token?

**Comment by morrissimo** [comment]
>How many bot applications are you running under the same token?

1

**Comment by morrissimo** [comment]
other bits:
* afk notices are enabled (using nucleus)
* topic updater is set to 60 seconds

**Comment by ziceptor** [comment]
Rarely. Same problem. https://gist.github.com/ziceptor/108b8f6620bd7e9bf1720f368a03a0d0

**Comment by Eufranio** [comment]
Hmm, looks like the server is stopping before the tasks are completed. As an workaround I'll try to execute the actions first, but I'm not sure if that will delay the server enough.

**Comment by Cebtenzzre** [comment]
@Eufranio Are you running async tasks _on shutdown_ and not waiting for them anywhere on the main thread (even in a GameStoppedServerEvent listener)?  (I haven't seen that part of the code before.)  Because that would mean you're lucky it even works right now, for _most people_, _without the topic updater_.
O/w, something really broken must be happening such that stuff on the main thread is getting interrupted.  I don't see how that could happen.

**Comment by Eufranio** [comment]
I am not, but looks like JDA/okhttp are. I can try to wait JDA to shutdown blocking the main thread though. I'll take a look soon.

**Comment by Eufranio** [comment]
Please test using the latest MagiBridge version: https://ore.spongepowered.org/Eufranio/MagiBridge/versions
