### ISSUE TITLE
Could not pass FMLPostInitializationEvent to Plugin

### ISSUE THREAD

**Issue by iamtpage** [Eufranio/MagiBridge#58]
Hi

I installed your plugin and when the server boots up the following stack trace is printed to the console:
```
[00:30:49] [Server thread/INFO] [magibridge]: MagiBridge is starting!
[00:30:51] [Server thread/DEBUG] [net.dv8tion.jda.core.requests.Requester]: Received response with following cf-rays: [3ee44c12189b1fbe-DFW]
[00:30:52] [Server thread/INFO] [net.dv8tion.jda.core.JDA]: Login Successful!
[00:30:52] [Server thread/DEBUG] [net.dv8tion.jda.core.requests.Requester]: Received response with following cf-rays: [3ee44c14faac1fbe-DFW]
[00:30:52] [JDA MainWS-ReadThread/INFO] [net.dv8tion.jda.core.requests.WebSocketClient]: Connected to WebSocket
[00:30:52] [JDA MainWS-ReadThread/DEBUG] [net.dv8tion.jda.core.requests.WebSocketClient]: Received new CF-RAY: 3ee44c164d651fac-DFW
[00:30:52] [JDA MainWS-ReadThread/DEBUG] [net.dv8tion.jda.core.requests.WebSocketClient]: Sending Identify-packet...
[00:30:52] [JDA MainWS-ReadThread/TRACE] [net.dv8tion.jda.core.requests.WebSocketClient]: <- {"op":2,"d":{"compress":true,"v":6,"presence":{"game":null,"afk":false,"since":1518823852715,"status":"online"},"large_threshold":250,"properties":{"$device":"JDA","$referring_domain":"","$os":"Linux","$browser":"JDA","$referrer":""},"token":"NDE0MDY0ODk3MjA3NDM1MjY1.DWh7jg.oxFd2agYD1hcPBiQGTtYVaa--aY"}}
[00:30:52] [JDA MainWS-ReadThread/DEBUG] [net.dv8tion.jda.core.requests.WebSocketClient]: Got HELLO packet (OP 10). Initializing keep-alive.
[00:30:52] [JDA MainWS-ReadThread/DEBUG] [net.dv8tion.jda.core.requests.WebSocketClient]: Received a _trace for HELLO (OP: 10) with ["gateway-prd-main-l3r0"]
[00:30:52] [JDA MainWS-KeepAlive Thread/TRACE] [net.dv8tion.jda.core.requests.WebSocketClient]: <- {"op":1,"d":0}
[00:30:52] [JDA MainWS-ReadThread/TRACE] [net.dv8tion.jda.core.requests.WebSocketClient]: Got Heartbeat Ack (OP 11).
[00:30:52] [JDA MainWS-ReadThread/TRACE] [net.dv8tion.jda.core.requests.WebSocketClient]: READY -> {"user_settings":{},"relationships":[],"_trace":["gateway-prd-main-l3r0","discord-sessions-prd-1-11"],"presences":[],"guilds":[],"v":6,"session_id":"3567fa2c3226281b702cd06fe206d6af","private_channels":[],"user":{"bot":true,"verified":true,"mfa_enabled":true,"id":"414064897207435265","avatar":"63018dd038795ab4b0531df20c6ff114","email":null,"username":"MCBot","discriminator":"7120"}}
[00:30:52] [JDA MainWS-ReadThread/DEBUG] [net.dv8tion.jda.core.requests.WebSocketClient]: Received a _trace for READY (OP: 0) with ["gateway-prd-main-l3r0","discord-sessions-prd-1-11"]
[00:30:52] [JDA MainWS-ReadThread/INFO] [net.dv8tion.jda.core.JDA]: Finished Loading!
[00:30:52] [JDA MainWS-ReadThread/DEBUG] [net.dv8tion.jda.core.requests.WebSocketClient]: Resending 0 cached events...
[00:30:52] [JDA MainWS-ReadThread/DEBUG] [net.dv8tion.jda.core.requests.WebSocketClient]: Sending of cached events finished.
[00:30:52] [Server thread/INFO] [magibridge]: Hooking into Nucleus
[00:30:52] [Server thread/ERROR] [Sponge]: Could not pass FMLPostInitializationEvent to Plugin{id=magibridge, name=MagiBridge, version=2.4.2, description=A utility Discord <-> Minecraft chat relay plugin, authors=[Eufranio], source=/home/container/mods/MagiBridge-API7-2.4.2.jar}
java.lang.NumberFormatException: The specified ID is not a valid snowflake (general). Expecting a valid long value!
	at net.dv8tion.jda.core.utils.MiscUtil.parseSnowflake(MiscUtil.java:139) ~[MiscUtil.class:?]
	at net.dv8tion.jda.core.utils.cache.SnowflakeCacheView.getElementById(SnowflakeCacheView.java:56) ~[SnowflakeCacheView.class:?]
	at net.dv8tion.jda.core.JDA.getTextChannelById(JDA.java:620) ~[JDA.class:?]
	at com.magitechserver.magibridge.DiscordHandler.isValidChannel(DiscordHandler.java:46) ~[DiscordHandler.class:?]
	at com.magitechserver.magibridge.DiscordHandler.sendMessageToChannel(DiscordHandler.java:19) ~[DiscordHandler.class:?]
	at com.magitechserver.magibridge.MagiBridge.initStuff(MagiBridge.java:139) ~[MagiBridge.class:?]
	at com.magitechserver.magibridge.MagiBridge.init(MagiBridge.java:92) ~[MagiBridge.class:?]
	at org.spongepowered.common.event.listener.GamePostInitializationEventListener_MagiBridge_init14.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2611-7.1.0-BETA-2916]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:335) [SpongeModEventManager.class:1.12.2-2611-7.1.0-BETA-2916]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:368) [SpongeModEventManager.class:1.12.2-2611-7.1.0-BETA-2916]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:213) [SpongeImpl.class:1.12.2-2611-7.1.0-BETA-2916]
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:240) [SpongeMod.class:1.12.2-2611-7.1.0-BETA-2916]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:725) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

MC: 1.12.2
SpongeForge: spongeforge-1.12.2-2611-7.1.0-BETA-2916
Magibridge: MagiBridge-API7-2.4.2

**Comment by Eufranio** [comment]
Use the channel ID in the config, not channel name (`general`).
