### ISSUE TITLE
Improve How to MagiBridge getting started documentation 

### ISSUE THREAD

**Issue by vorburger** [Eufranio/MagiBridge#69]
I'm trying to follow https://github.com/Eufranio/MagiBridge#how-to-magibridge but so far haven't been able to get it working... perhaps that documentation with the initial steps could be improved?  I would be happy to contribute to this project and help with that - once I get it working for myself... :smiley: 

So far I have, as suggested, created a new app, and a bot for that app, and put that token into `bot-token=`. I then gather that you need a channel, so [I created a new server](https://discord.gg/NPbutxm), Discord gave it a #general channel, and by [Enabling Discord Developer Mode](https://discordia.me/developer-mode) and right-click "Copy ID" on #general in my server I got 443936651102781473 - which is also in [the 2nd part of the URL of this channel on my server](https://discordapp.com/channels/443936651102781471/443936651102781473). So I put `main-discord-channel="443936651102781473"` but that is given me the errors below - what am I missing?

```
[03:44:03 ERROR] [magibridge]: The channel 443936651102781473 defined in the config isn't a valid Discord Channel ID!
[03:44:03 ERROR] [magibridge]: Replace it with a valid one then reload the plugin!
[03:44:03 INFO] [Sponge]: Successfully loaded and initialized plugins.
[03:44:03 ERROR] [magibridge]: The main-discord-channel is INVALID, replace it with a valid one and restart the server!
[03:44:03 ERROR] [magibridge]: The main-discord-channel is INVALID, replace it with a valid one and restart the server!
[03:44:03 ERROR] [magibridge]: The main-discord-channel is INVALID, replace it with a valid one and restart the server!
```

**Comment by Eufranio** [comment]
Did you add the bot to your server first?

**Comment by vorburger** [comment]
> Did you add the bot to your server first?

@Eufranio oh! Nope, I had no idea... :smiley: sorry. As per https://github.com/jagrosh/MusicBot/wiki/Adding-Your-Bot-To-Your-Server, I did the following (writing this down for copy/paste to a future PR to update README):

> Find [the Client ID of the new App](https://discordapp.com/developers/applications/me) and 
Replace the CLIENTID in the following link with your bot's client ID:
`https://discordapp.com/oauth2/authorize?client_id=CLIENTID&scope=bot` (for example, if you bot's Client ID is `168682538028630017`, your link would be `https://discordapp.com/oauth2/authorize?client_id=168682538028630017&scope=bot`), select Your Server from the drop-down menu, and Authorize. You must have the Manage Server permission to add a bot to a server! 

with that I'm now hitting this:

```
[15:24:11 INFO] [magibridge]: MagiBridge is starting!
[15:24:12 INFO] [net.dv8tion.jda.core.JDA]: Login Successful!
[15:24:12 INFO] [net.dv8tion.jda.core.requests.WebSocketClient]: Connected to WebSocket
[15:24:14 INFO] [net.dv8tion.jda.core.JDA]: Finished Loading!
[15:24:14 INFO] [magibridge]: Hooking into Nucleus
[15:24:14 INFO] [Sponge]: Successfully loaded and initialized plugins.
[15:24:14 ERROR] [STDERR]: Exception in thread "MagiBridge Topic Updater" net.dv8tion.jda.core.exceptions.InsufficientPermissionException: Cannot perform action due to a lack of Permission. Missing permission: MANAGE_CHANNEL
[15:24:14 ERROR] [STDERR]: 	at net.dv8tion.jda.core.managers.ChannelManagerUpdatable.checkPermission(ChannelManagerUpdatable.java:377)
[15:24:14 ERROR] [STDERR]: 	at net.dv8tion.jda.core.managers.ChannelManagerUpdatable.update(ChannelManagerUpdatable.java:327)
[15:24:14 ERROR] [STDERR]: 	at net.dv8tion.jda.core.managers.ChannelManager.setTopic(ChannelManager.java:197)
[15:24:14 ERROR] [STDERR]: 	at com.magitechserver.magibridge.util.TopicUpdater.run(TopicUpdater.java:35)
```

BTW: Perhaps the intro doc should clarify whether to use `use-webhooks=` `true`or `false` ?

PS Sandvoxel on MagiBridge #general pointed to [Where can I find my User/Server/Message ID?](https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-), which we could also add to the README.

**Comment by vorburger** [comment]
> with that I'm now hitting this:
> Exception in thread "MagiBridge Topic Updater" net.dv8tion.jda.core.exceptions.InsufficientPermissionException: Cannot perform action due to a lack of Permission. Missing permission: MANAGE_CHANNEL

Here's how to fix that:

* On _Server Settings_, in _Roles_, create a _New Role_ named e.g. "bot", give it the _Manage Channels_ permission, and in _Members_ grant your Bot that role
