### ISSUE TITLE
java.lang.NoClassDefFoundError: nl/riebie/mcclans/channels/ClanMessageChannelImpl

### ISSUE THREAD

**Issue by vorburger** [Eufranio/MagiBridge#76]
I'm hitting the exception below, with a `MagiBridge-2.4.5.1.jar` I self built from source (due to #73) today from branch `api-7` as of 29b39020fd35371272368c782cd459b08e715ec3 running in `spongevanilla-1.12.2-7.1.0-BETA-33.jar` :

```
[21:08:16 INFO]: UUID of player charlotte_2005_ is e74e28fe-6079-4c8e-8ccb-5f6b1f5f681b
[21:08:17 INFO]: charlotte_2005_[/172.17.0.1:56460] logged in with entity id 1666 in world(0) at (-159.5, 68.0, 248.5)
[21:08:18 INFO]: Welcome charlotte_2005_ to the server!
[21:08:19 INFO]: charlotte_2005_ joined the game
[21:08:19 WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2275ms behind, skipping 45 tick(s)
[21:08:31 ERROR] [Sponge]: Could not pass MessageChannelEvent$Chat$Impl to Plugin{id=magibridge, name=MagiBridge, version=2.4.5.1, description=A utility Discord <-> Minecraft chat relay plugin, authors=[Eufranio], source=mods/MagiBridge-2.4.5.1.jar}
java.lang.NoClassDefFoundError: nl/riebie/mcclans/channels/ClanMessageChannelImpl
	at com.magitechserver.magibridge.listeners.SpongeChatListener.onSpongeMessage(SpongeChatListener.java:40) ~[SpongeChatListener.class:?]
	at org.spongepowered.common.event.listener.ChatListener_SpongeChatListener_onSpongeMessage103.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-7.1.0-BETA-33]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:408) [SpongeEventManager.class:1.12.2-7.1.0-BETA-33]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:435) [SpongeEventManager.class:1.12.2-7.1.0-BETA-33]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:427) [SpongeEventManager.class:1.12.2-7.1.0-BETA-33]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207) [SpongeImpl.class:1.12.2-7.1.0-BETA-33]
	at net.minecraft.network.NetHandlerPlayServer.handler$onProcessChatMessage$zpm000(SourceFile:2522) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(SourceFile:845) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-7.1.0-BETA-33]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zkn000(SourceFile:539) [hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:276) [SpongeImplHooks.class:1.12.2-7.1.0-BETA-33]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjc000(SourceFile:4149) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1580) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:349) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:464) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.ClassNotFoundException: nl.riebie.mcclans.channels.ClanMessageChannelImpl
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_161]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_161]
	... 24 more
Caused by: java.lang.NullPointerException
[21:08:31 INFO]: charlotte_2005_: ciao
```

Indeed the JAR does not contain `nl/...` so this NoClassDefFoundError "make senses" - shadow problem?

**Comment by vorburger** [comment]
> running in spongevanilla-1.12.2-7.1.0-BETA-33.jar :

I'm not 100% sure but I believe when I previously tested this with a `spongevanilla-1.12.2-7.1.0-BETA-13.jar` I did not get his error... or perhaps I have changed something else which is now causing it and did not before. Anyway, having a closer look at the code:

    java.lang.NoClassDefFoundError: nl/riebie/mcclans/channels/ClanMessageChannelImpl
     	at com.magitechserver.magibridge.listeners.SpongeChatListener.onSpongeMessage(SpongeChatListener.java:40) ~[SpongeChatListener.class:?]

that's just some check for some old 3rd party plugin, I don't use anyway, and only used here:

```java
if (Sponge.getPluginManager().isLoaded("mcclans") && e.getChannel().get() instanceof AllyMessageChannelImpl || e.getChannel().get() instanceof ClanMessageChannelImpl) {
    return;
```

not sure I really understand how this is supposed to work (with that plugin not shadowed in the JAR) - doesn't this assume one has to have that plugin installed?!

I guess I could figure out hwo to bundle it in this plugin's JAR, but... the lib/mcclans.jar also includes io.github.nucleuspowered - this smells like a mess? If only anyone else would use https://github.com/vorburger/ch.vorburger.minecraft.osgi ! ;-)

The easiest, for me at least, is to just remove this.

**Comment by Eufranio** [comment]
This code only gets called when `Sponge.getPluginManager().isLoaded("mcclans")` is true, which is when the MCClans (plugin containing the ClanMessageChannelImpl class) is load and have this class in the classpath. I never had problems with this before, can you reproduce it?

**Comment by vorburger** [comment]
Yes I can reproduce this. In Java, AFAIK, the mcclans classes have to be on the class path for that listener class itself to be able to load, not just when that part of the end of the if line is executed.

**Comment by Eufranio** [comment]
Nope. I do the exact same thing with the Boop integration, and it works just fine: https://github.com/Eufranio/MagiBridge/blob/master/src/main/java/com/magitechserver/magibridge/NucleusHandler.java#L31

Or here, I call this method many times from many places: https://github.com/Eufranio/MagiBridge/blob/master/src/main/java/com/magitechserver/magibridge/NucleusHandler.java#L95

**Comment by Cebtenzzre** [comment]
Dude.  Two words: Operator precedence.
Look it up if you don't believe me, but you have to put the ORed `instanceof` expressions _inside_ of some parentheses, or else the second `instanceof` will be short-circuit evaluated immediately after the `isLoaded` check if `isLoaded` returns false, causing a NoClassDefFoundError.  Boolean logic in most programming languages has been done this way since C was created in the 1970s.

No offense, but this is why I tell people to learn how to write code before they learn how to write mods or plugins.  And if you're using plugins to learn, start by focusing on the _language itself_.  For example, I see far too many people not using lambdas in Java 8 just because they never bothered to learn how to use them.
